version: 2
jobs:
  build:
    working_directory: ~/repo
    parallelism: 1

    docker:
      - image: circleci/rust:1.39

    steps:
      - checkout

      - restore_cache:
          keys:
            - dep-{{ checksum "Cargo.toml" }}

      - run:
          name: build
          command: cargo build --release

      - save_cache:
          key: dep-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo

      - run:
          name: test
          command: |
            mkdir var/
            RUST_BACKTRACE=1 cargo test

      - save_cache:
          key: dep-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo

workflows:
  version: 2
  build_all:
    jobs:
      - build
